spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/store
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    drop-first: true
    change-log: classpath:db.changelog/db.changelog-master.yml
    enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html